[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/kuwa"]

[project]
name = "kuwa-executor"
version = "0.1.0"
authors = [
  { name="Drift", email="taifu9920923@gmail.com" },
  { name="Yung-Hsiang Hu", email="iftnt1999@gmail.com" },
]
description = "A framework to serve the Kuwa Executors, including LLM model worker."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies=[
  'fastapi~=0.110.0',
  'prometheus_client~=0.20.0',
  'python-multipart~=0.0.9',
  'requests~=2.31.0',
  'retry~=0.9.2',
  'uvicorn[standard]~=0.29.0'
]

[project.urls]
"Homepage" = "https://kuwaai.org/os/Intro"
"Bug Tracker" = "https://github.com/kuwaai/genai-os/issues"

# [project.scripts]
# worker-server = "worker_framework.main:main"