services:
  docqa-executor:
    build:
      context: ../
      dockerfile: docker/executor/Dockerfile
    image: kuwa-executor
    environment:
      CUSTOM_EXECUTOR_PATH: ./docqa/docqa.py
      EXECUTOR_ACCESS_CODE: doc-qa;web-qa
      EXECUTOR_NAME: DocQA;WebQA
    depends_on:
      - kernel
      - multi-chat
    command: [
      "--api_base_url", "http://web/",
      "--model", "llama3",
      #"--model", "gemini-pro"
      ]
    extra_hosts:
      - "localhost:host-gateway"
    restart: unless-stopped
    networks: ["backend", "frontend"]