services:
  gemini-executor:
    build:
      context: ../
      dockerfile: docker/executor/Dockerfile
    image: kuwa-executor
    environment:
      EXECUTOR_TYPE: geminipro
      EXECUTOR_ACCESS_CODE: gemini-pro
      EXECUTOR_NAME: Gemini Pro
    depends_on:
      - kernel
      - multi-chat
    command: []
    restart: unless-stopped
    networks: ["backend"]